[2017-05-18 10:08:03.739] [ERROR] logErr - 执行sql发生错误：INSERT INTO bd_classinfo (class_id,class_name,grade_id,grade_name,server_id,server_name,description,school_year)VALUES('001', '六年级', 'undefined', 'undefined', 'undefined', '央直', '国家重点院校', '6') ,('002', 'undefined', '020', '北京市委', '2000', '直属', '重点院校', '7') ,('003', '三年级', '030', '北市委', '3000', '中央', '国家院校', 'undefined') /n 错误信息：Error: ER_DUP_ENTRY: Duplicate entry '001' for key 'PRIMARY'
    at Query.Sequence._packetToError (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:199:23)
    at Queries.query (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:10:9)
    at Object.queryStrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:25:16)
    at Object.saveInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\classDao.js:28:20)
    at Object.saveUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\classService.js:25:18)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\classRoute.js:11:18
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
    at next (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
[2017-05-18 10:08:03.755] [ERROR] logErr - 错误信息：Error: ER_DUP_ENTRY: Duplicate entry '001' for key 'PRIMARY'
    at Query.Sequence._packetToError (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:199:23)
    at Queries.query (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:10:9)
    at Object.queryStrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:25:16)
    at Object.saveInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\classDao.js:28:20)
    at Object.saveUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\classService.js:25:18)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\classRoute.js:11:18
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
    at next (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
[2017-05-18 10:15:01.067] [ERROR] logErr - 执行sql发生错误：INSERT INTO bd_organ (organ_id,organ_name,is_root,has_child,p_organ_id,p_organ_name)VALUES('001', '北京市委', '1', '0', 'undefined', '010', '中央直属') ,('002', '北京市', '1', '0', 'undefined', '020', '中央直属') ,('003', '市委', '1', '0', 'undefined', '030', '中央') /n 错误信息：Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:199:23)
    at Queries.query (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:10:9)
    at Object.queryStrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:25:16)
    at Object.saveInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\organ_coDao.js:28:20)
    at Object.saveUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\organ_coService.js:25:21)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\organ_coRoute.js:11:21
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
    at next (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
[2017-05-18 10:15:01.078] [ERROR] logErr - 错误信息：Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:199:23)
    at Queries.query (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:10:9)
    at Object.queryStrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:25:16)
    at Object.saveInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\organ_coDao.js:28:20)
    at Object.saveUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\organ_coService.js:25:21)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\organ_coRoute.js:11:21
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
    at next (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
[2017-05-18 10:21:38.154] [ERROR] logErr - 执行sql发生错误：INSERT INTO bd_organ (organ_id,organ_name,is_root,has_child,p_organ_id,p_organ_name)VALUES('001', '北京市委', '0', '1', '010', '中央fff直属') ,('002', '北京市', '0', '0', '021', 'undefined') ,('003', '市委', '0', 'undefined', 'undefined', 'undefined') /n 错误信息：Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'undefined' for column 'has_child' at row 3
    at Query.Sequence._packetToError (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:199:23)
    at Queries.query (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:10:9)
    at Object.queryStrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:25:16)
    at Object.saveInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\organ_coDao.js:28:20)
    at Object.saveUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\organ_coService.js:25:21)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\organ_coRoute.js:11:21
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
    at next (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
[2017-05-18 10:21:38.159] [ERROR] logErr - 错误信息：Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'undefined' for column 'has_child' at row 3
    at Query.Sequence._packetToError (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:199:23)
    at Queries.query (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:10:9)
    at Object.queryStrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:25:16)
    at Object.saveInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\organ_coDao.js:28:20)
    at Object.saveUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\organ_coService.js:25:21)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\organ_coRoute.js:11:21
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
    at next (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
[2017-05-18 10:53:03.028] [ERROR] logErr - 执行sql发生错误：INSERT INTO bd_parentinfo (user_id,true_name,server_id,server_name,sex,child_id,phone,job,email,child_name)VALUES('001', 'hhh', '010', 'bbb', '0', '00001', '2222222222222', '', '', 'bbbb') ,('002', 'bbb', '012', 'bbb', '1', '00002', '1111111111111', 'work', '', 'qqqq') ,('003', 'ccc', '016', 'bbb', '0', '00003', '5555555555555', 'ffff', '', 'cccc') /n 错误信息：Error: ER_DUP_ENTRY: Duplicate entry '001' for key 'PRIMARY'
    at Query.Sequence._packetToError (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:199:23)
    at Queries.query (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:10:9)
    at Object.queryStrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:25:16)
    at Object.saveInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\parentDao.js:28:20)
    at Object.saveUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\parentService.js:25:19)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\parentRoute.js:11:19
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
    at next (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
[2017-05-18 10:53:03.042] [ERROR] logErr - 错误信息：Error: ER_DUP_ENTRY: Duplicate entry '001' for key 'PRIMARY'
    at Query.Sequence._packetToError (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Pool.query (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:199:23)
    at Queries.query (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:10:9)
    at Object.queryStrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:25:16)
    at Object.saveInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\parentDao.js:28:20)
    at Object.saveUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\parentService.js:25:19)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\parentRoute.js:11:19
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
    at next (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:110:13)
    at Route.dispatch (F:\work\QHPG-BJDF\node_modules\express\lib\router\route.js:91:3)
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
[2017-05-18 10:57:10.092] [ERROR] logErr - 执行sql发生错误：UPDATE bd_parentinfo SET true_name='hhh',server_id='010',server_name='bbb',sex='0',child_id='00001',phone='2222222222222',job='',email='',child_name='bbbb' WHERE user_id='001';,UPDATE bd_parentinfo SET true_name='bbb',server_id='012',server_name='bbb',sex='1',child_id='00002',phone='1111111111111',job='work',email='',child_name='qqqq' WHERE user_id='002';,UPDATE bd_parentinfo SET true_name='ccc',server_id='016',server_name='bbb',sex='0',child_id='00003',phone='5555555555555',job='ffff',email='',child_name='cccc' WHERE user_id='003';/n 错误信息：Error: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:419:13)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:342:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    --------------------
    at Protocol._enqueue (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Protocol.handshake (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at PoolConnection.connect (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:48:16)
    at Queries.queries (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:19:9)
    at Object.queryArrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:49:16)
    at Object.updataInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\parentDao.js:57:20)
    at Object.updataUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\parentService.js:65:19)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\parentRoute.js:19:19
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
[2017-05-18 10:57:10.100] [ERROR] logErr - 错误信息：Error: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:419:13)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:342:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    --------------------
    at Protocol._enqueue (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Protocol.handshake (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at PoolConnection.connect (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:48:16)
    at Queries.queries (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:19:9)
    at Object.queryArrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:49:16)
    at Object.updataInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\parentDao.js:57:20)
    at Object.updataUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\parentService.js:65:19)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\parentRoute.js:19:19
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
[2017-05-18 10:57:28.067] [ERROR] logErr - 执行sql发生错误：UPDATE bd_parentinfo SET true_name='hhh',server_id='010',server_name='bbb',sex='0',child_id='00001',phone='2222222222222',job='',email='',child_name='bbbb' WHERE user_id='001';,UPDATE bd_parentinfo SET true_name='bbb',server_id='012',server_name='bbb',sex='1',child_id='00002',phone='1111111111111',job='work',email='',child_name='qqqq' WHERE user_id='002';,UPDATE bd_parentinfo SET true_name='ccc',server_id='016',server_name='bbb',sex='0',child_id='00003',phone='5555555555555',job='ffff',email='',child_name='cccc' WHERE user_id='003';/n 错误信息：Error: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:419:13)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:342:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    --------------------
    at Protocol._enqueue (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Protocol.handshake (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at PoolConnection.connect (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:48:16)
    at Queries.queries (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:19:9)
    at Object.queryArrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:49:16)
    at Object.updataInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\parentDao.js:57:20)
    at Object.updataUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\parentService.js:65:19)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\parentRoute.js:19:19
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
[2017-05-18 10:57:28.068] [ERROR] logErr - 错误信息：Error: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:419:13)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:342:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    --------------------
    at Protocol._enqueue (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Protocol.handshake (F:\work\QHPG-BJDF\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at PoolConnection.connect (F:\work\QHPG-BJDF\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (F:\work\QHPG-BJDF\node_modules\mysql\lib\Pool.js:48:16)
    at Queries.queries (F:\work\QHPG-BJDF\node_modules\mysql-queries\lib\mysql-queries.js:19:9)
    at Object.queryArrSql (F:\work\QHPG-BJDF\util\mysqlUtil.js:49:16)
    at Object.updataInfo (F:\work\QHPG-BJDF\dao\bdmanage_dao\parentDao.js:57:20)
    at Object.updataUserInfo (F:\work\QHPG-BJDF\service\bdmanage_service\parentService.js:65:19)
    at F:\work\QHPG-BJDF\routes\bdmanage_route\parentRoute.js:19:19
    at Layer.handle [as handle_request] (F:\work\QHPG-BJDF\node_modules\express\lib\router\layer.js:82:5)
